### ISSUE TITLE
generalize allowed date formats

### ISSUE THREAD

**Issue by smrgeoinfo** [isamplesorg/isamples_inabox#389]
generalize dates to allow YYYY, YYYY-MM, YYYY-MM-DD, YYYY-MM-DDThh-mm etc....
Update LinkML and JSON schema.

In JSON schema want:
```
"anyOf": [
                        {
                            "format": "date",
                            "description": "YYYY-MM-DD"
                        },
                        {
                            "format": "date-time",
                            "description": "YYYY:MM::DDThh:mm:ss.sTZD"
                        },
                        {
                            "pattern": "^(?:[1]?[0-9]{3}|20[0-2][0-9])$",
                            "description": "gets YYYY"
                        },
                        {
                            "pattern": "^(?:[1]?[0-9]{3}|20[0-2][0-9])-(?:0[1-9]|1[0-2])$",
                            "description": "gets YYYY-MM"
                        }
                    ],
```

looks like pattern is the corresponding LinkML schema slot property for the regex statements

**Comment by smrgeoinfo** [comment]
In YAML LinkML schema, update restult_time to 

```
result_time:
    range: string
    any_of:
       - range: date
       - range: datetime
       - pattern: "^(?:[1]?[0-9]{3}|20[0-2][0-9])$"
       - pattern: "^(?:[1]?[0-9]{3}|20[0-2][0-9])-(?:0[1-9]|1[0-2])$"
    domain: SamplingEvent
    description: >
      Date on which the sample was collected. Can be YYYY, YYYY-MM, xsd:date, or xsd:dateTime.
```
